### PR TITLE
Preserve shopify params on redirect to authentication

### PR DESCRIPTION
**Pull request by quaspas**
Without preserving the `shop` param we will be kicked back to the install page.

Thank you for the library :)

### CODE REVIEW

**Comment by ericdude4** [comment]
Can you explain the scenario which causes you to be kicked back to the install page? It has been working for me without preserving the `shop` param. However, the PR seems logical and certainly didn't break the (my) existing behaviour. Thanks for the PR :)

**Comment by quaspas** [comment]
You are welcome, appreciate the quick review :)

What I was seeing was after install logs like:
```
21:02:16.349 request_id=Fhg2RI5UerwsxM8AAAFh [info] GET /auth/install
21:02:16.864 request_id=Fhg2RI5UerwsxM8AAAFh [info] All current webhook topics for teststore.myshopify.com:
21:02:16.864 request_id=Fhg2RI5UerwsxM8AAAFh [info] subscribing to topic app/uninstalled
21:02:17.279 request_id=Fhg2RI5UerwsxM8AAAFh [info] Sent 302 in 930ms
21:02:23.214 request_id=Fhg2RieJnFFRIUoAAAFx [info] GET /
21:02:23.214 request_id=Fhg2RieJnFFRIUoAAAFx [info] Sent 302 in 391µs
21:02:23.243 request_id=Fhg2RilAXbJGc_EAAAGB [info] GET /auth
21:02:23.243 request_id=Fhg2RilAXbJGc_EAAAGB [info] Sent 200 in 687µs
21:02:28.203 request_id=Fhg2R1DtXDNE3jsAAAGR [info] GET /
21:02:28.204 request_id=Fhg2R1DtXDNE3jsAAAGR [info] Sent 302 in 248µs
21:02:28.230 request_id=Fhg2R1J-gKP0u6oAAAGh [info] GET /auth
21:02:28.230 request_id=Fhg2R1J-gKP0u6oAAAGh [info] Sent 200 in 638µs
21:02:38.667 request_id=Fhg2ScCVmIIZILgAAAGx [info] GET /info
21:02:38.667 request_id=Fhg2ScCVmIIZILgAAAGx [info] Sent 200 in 604µs
21:02:41.057 request_id=Fhg2Sk8Ss4-dXUYAAAHB [info] GET /
21:02:41.058 request_id=Fhg2Sk8Ss4-dXUYAAAHB [info] Sent 302 in 409µs
21:02:41.076 request_id=Fhg2SlAvUBt2CxMAAAHR [info] GET /auth
21:02:41.076 request_id=Fhg2SlAvUBt2CxMAAAHR [info] Sent 200 in 562µs
21:03:58.412 request_id=Fhg2XFHHmIaE4tYAAAHh [info] GET /
21:03:58.412 request_id=Fhg2XFHHmIaE4tYAAAHh [info] Sent 302 in 317µs
21:03:58.431 request_id=Fhg2XFLkuAtfbsoAAAHx [info] GET /auth
21:03:58.431 request_id=Fhg2XFLkuAtfbsoAAAHx [info] Sent 200 in 620µs
21:06:16.213 request_id=Fhg2fGdcdrHZ5PQAAAIB [info] GET /
21:06:16.213 request_id=Fhg2fGdcdrHZ5PQAAAIB [info] Sent 302 in 473µs
21:06:16.235 request_id=Fhg2fGipsLHD3fMAAAIR [info] GET /auth
21:06:16.236 request_id=Fhg2fGipsLHD3fMAAAIR [info] Sent 200 in 700µs
21:06:37.262 request_id=Fhg2gU30GbnEOIsAAAIh [info] GET /auth
21:06:37.262 request_id=Fhg2gU30GbnEOIsAAAIh [info] Sent 200 in 573µs
21:06:39.018 request_id=Fhg2gbaiFISI9rcAAAIx [info] GET /auth
21:06:39.021 request_id=Fhg2gbaiFISI9rcAAAIx [info] Sent 403 in 2ms
```

The app installs and then after redirecting can't authenticate.

I think what might also have worked was to call `put_flash(conn, :shop, shop)` [before the install completes and redirects](https://github.com/ericdude4/shopifex/blob/master/lib/shopifex_web/controllers/auth_controller.ex#L83-L93).

I am not sure what scenario I would have needed to already have the `:shop` set otherwise.
https://github.com/ericdude4/shopifex/blob/master/lib/shopifex/plug/shopify_session.ex#L17

**Comment by ericdude4** [comment]
@quaspas What does your router look like? I wonder if your `/` route was piped through the `Shopifex.Plug.ShopifyEntrypoint` plug. It's supposed to redirect to `/` after install, then that route should use the `Shopifex.Plug.ShopifySession` plug. I think it's shown in the README

**Comment by quaspas** [comment]
I only have my `/auth` scope piped through `shopify_entrypoint`

My full router:

```
defmodule AppWeb.Router do
  use AppWeb, :router

  pipeline :shop_browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug Shopifex.Plug.FetchFlash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Shopifex.Plug.LoadInIframe
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", AppWeb do
    pipe_through :browser

    get "/info", PageController, :info
  end


  # Ensures that a valid store is currently loaded in the session and is accessible in your
  # controllers/templates as `conn.private.shop`
  pipeline :shopify_session do
    plug Shopifex.Plug.ShopifySession
  end

  # Make sure the incoming requests from Shopify are valid. For example, when the app is
  # being installed, or the initial loading of your App inside of the Shopify admin panel.
  pipeline :shopify_entrypoint do
    plug Shopifex.Plug.ShopifyEntrypoint
  end

  # Ensures that the connection has a valid Shopify webhook HMAC token
  pipeline :shopify_webhook do
    plug Shopifex.Plug.ShopifyWebhook
  end

  scope "/auth", AppWeb do
    pipe_through [:shop_browser, :shopify_entrypoint]
    get "/", AuthController, :auth
    get "/install", AuthController, :install
  end

  scope "/", AppWeb do
    pipe_through [:shop_browser, :shopify_session]

    get "/", PageController, :index
  end

  scope "/webhook", AppWeb do
    pipe_through [:shopify_webhook]

    post "/", WebhookController, :action
  end
end
```

**Comment by ericdude4** [comment]
@quaspas Yea your router looks great... What are your config options? The `:shop` param gets placed in the session in the `AuthController`, then re-set inside of the `Shopifex.Plug.ShopifySession`. This has worked great for me. Whats your config look like?

**Comment by quaspas** [comment]
My config for shopifex:

```
# config.exs
...
config :shopifex,
  app_name: "myapp",
  shop_schema: Db.Shop,
  repo: Db.Repo,
  redirect_uri: "https://myapp123.ngrok.io/auth/install", # This should be in your Shopify app's whitelist
  webhook_uri: "https://myapp123.ngrok.io/webhook",
  scopes: "read_customers,read_orders,read_all_orders,read_draft_orders,read_products",
  api_key: "shopifyapikey123", # Change this value to your Shopify api key from before
  secret: "shopifyapisecret456", # Change this value to your Shopify api secret from before
  webhook_topics: ["app/uninstalled"]
...

# prod.exs
config :shopifex,
  app_name: "myapp",
  redirect_uri: "https://mywebsite.com/auth/install",
  webhook_uri: "https://mywebsite.com/webhook"
...

# release.exs
config :shopifex,
  api_key: System.get_env("SHOP_API_KEY", "SHOP_API_KEY_NOT_SET"),
  secret: System.get_env("SHOP_SECRET", "SHOP_SECRET_NOT_SET")
...
```

**Pull request merged**
